### ISSUE TITLE
Dragon Tower

### ISSUE THREAD

**Issue by RazzSG** [Malekitsu/MM6-Nightmare-Mode#1]
Hi, the dragon tower model in Blackshire is missing. But it still shoots a fireball.
![image](https://github.com/Malekitsu/MM6-Nightmare-Mode/assets/51904365/9623c002-5a0f-478b-8cc6-68e0d8647802)

**Comment by Malekitsu** [comment]
Thanks for feedback,
The tower has been moved East from city.
I will fix projectile starting location

**Comment by Malekitsu** [comment]
fixed
