### ISSUE TITLE
Error since MMExtension update on Mar 8, 2024

### ISSUE THREAD

**Issue by w0lv** [Malekitsu/MM6-Nightmare-Mode#2]
I am encountering an error upon being hit by an enemy spell with the latest versions of MMExtension. This appears to be related to the change in MMExtension commit `d9eb388ed10bed93d024d7754802fe3a379f3029` "Use CalcSpellDamage when party is hit by an event spell", committed on Mar 8, 2024.

If I roll MMExtension back to the commit directly prior to that one, `e05c2623436d27d8cfc00d2268b8756340220ab2`, then I'm able to take enemy spell damage without error.

Below is the error I receive with `d9eb38` and later
```
...\Scripts\General\maw-spell-overrides.lua:1037: attempt to index global 'data' (a nil value)

stack traceback:
	...\Scripts\General\maw-spell-overrides.lua: in function 'v'
	...\Scripts/Core/EventsList.lua:102: in function <...\Scripts/Core/EventsList.lua:97>

arguments of 'v':
	(*temporary) = (table: 0x102fb3c8)

local variables of 'v':
	(*temporary) = (table: 0x03bc84d0)
	(*temporary) = nil
	(*temporary) = nil
	(*temporary) = nil
	(*temporary) = nil
	(*temporary) = nil
	(*temporary) = nil
	(*temporary) = "attempt to index global 'data' (a nil value)"

upvalues of 'v':
	spellPowers = (table: 0x03bc7ed0)
	randomSpellPower = (function: 0x03b91800)
```

**Comment by w0lv** [comment]
Opened a PR with a tentative fix. I'm unsure why the CalcSpellDamage changes appeared to cause the behavior. Perhaps there is some interaction you may see, or perhaps it was a red herring

**Comment by Malekitsu** [comment]
hey!
Unfortunately new MMExtension version doesn't work with current code.
I gave a quick check, but your fix looks like that only stops errors, but doesn't let spells run the original code.
We are still evaluating if distribute older mmextension version or adapt the code to correctly use the new code.
Meanwhile you can use this one and redrag MAW into your mm6 folder.
[MMExtension-master_MAW.zip](https://github.com/Malekitsu/MM6-Nightmare-Mode/files/14809494/MMExtension-master_MAW.zip)

**Comment by w0lv** [comment]
Ah, ok. That makes sense. Apologies then, I'm not super familiar with MM modding in general

Please feel free to close the issue and PR, or let me know if you'd like me to do so

Thank you for the tweaked MMExt and for your time

**Comment by Malekitsu** [comment]
Don't worry, thanks for pointing out ;)
I'll keep open until we either change link in readme or adapt the code

**Comment by Malekitsu** [comment]
release 2.2.1 version with fix.
Should be working good now.
